/*
 * Infineon BGT60ATR24C register definitions
 * Based on BGT60ATR24C Datasheet V1.6
 */
#ifndef BGT60ATR24C_REGS_H
#define BGT60ATR24C_REGS_H

/* MAIN register bank (7-bit SPI addresses) */
#define BGT60_REG_MAIN		0x00
#define BGT60_REG_CHIP_VERSION	0x02
#define BGT60_REG_SFCTL		0x06
#define BGT60_REG_FSTAT		0x5f
#define BGT60_REG_CHIP_ID1	0x60
#define BGT60_REG_CHIP_ID2	0x61
#define BGT60_FIFO_ADDR		0x62

#define BGT60_REG_WIDTH		3

/* MAIN bits (W1C) */
#define BGT60_MAIN_FRAME_START	BIT(0)
#define BGT60_MAIN_SW_RESET	BIT(1)
#define BGT60_MAIN_FSM_RESET	BIT(2)
#define BGT60_MAIN_FIFO_RESET	BIT(3)

/* SFCTL bit fields */
#define BGT60_SFCTL_QSPI_WT_SHIFT	20
#define BGT60_SFCTL_QSPI_WT_MASK	(0xf << BGT60_SFCTL_QSPI_WT_SHIFT)
#define BGT60_SFCTL_LFSR_EN		BIT(17)
#define BGT60_SFCTL_PREFIX_EN		BIT(18)
#define BGT60_SFCTL_FIFO_CREF_SHIFT	0
#define BGT60_SFCTL_FIFO_CREF_MASK	0x1fff

/* FSTAT bit fields */
#define BGT60_FSTAT_FOF_ERR		BIT(23)
#define BGT60_FSTAT_FUF_ERR		BIT(19)
#define BGT60_FSTAT_BURST_ERR		BIT(18)
#define BGT60_FSTAT_CLK_NUM_ERR		BIT(17)
#define BGT60_FSTAT_FILL_STATUS_SHIFT	0
#define BGT60_FSTAT_FILL_STATUS_MASK	0x1fff

#define BGT60_QSPI_ADDR_MAX		0xbf

#define BGT60_FRAME_FLAG_FOF_ERR	BIT(0)
#define BGT60_FRAME_FLAG_BURST_ERR	BIT(1)
#define BGT60_FRAME_FLAG_CLK_NUM_ERR	BIT(2)

#endif /* BGT60ATR24C_REGS_H */
